server:
  tomcat:
    uri-encoding: UTF-8
spring:
  #=====DataBase \u76F8\u5173===========
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/deeplearning?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: xieyc@mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # \u914D\u7F6E\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684filters\uFF0C'stat'\u7528\u4E8E\u76D1\u63A7\u7EDF\u8BA1;  'log4j'\u7528\u4E8E\u65E5\u5FD7;  'wall'\u7528\u4E8E\u9632\u706B\u5899
    druid:
      filters: stat,wall,config,log4j
      use-global-data-source-stat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  #=====Redis\u76F8\u5173========
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 10000ms    # \u6307\u5B9A\u8D85\u65F6\u65F6\u95F4
    jedis:
      pool:
        min-idle: 1     # \u8FDE\u63A5\u6C60\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5
        max-idle: 5     # \u8FDE\u63A5\u6C60\u6700\u5927\u7A7A\u95F2\u8FDE\u63A5
        max-active: 10  # \u8FDE\u63A5\u6C60\u6700\u5927\u8FDE\u63A5\u6570(\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236)
        max-wait: -1    # \u8FDE\u63A5\u6C60\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4(\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236)

#===== Mybatis-plus \u76F8\u5173 =====
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  type-aliases-package: com.yc.core.*.entity
  configuration:
    map-underscore-to-camel-case: true  # \u9A7C\u5CF0
  global-config:
    banner: false #\u5173\u95EDMP 3.0 \u81EA\u5E26\u7684banner

dl:
  #===== \u4E0A\u4F20\u4E0B\u8F7D \u76F8\u5173 =====
  upload:
    img-save-path: D://upload//image//
    img-access-path: /image/**
    file-save-path: D://upload//file//
    file-access-path: /file/**
