server:
  tomcat:
    uri-encoding: UTF-8
spring:
  #=====Redis 相关========
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 10000ms    # \u6307\u5B9A\u8D85\u65F6\u65F6\u95F4
    jedis:
      pool:
        min-idle: 1     # 连接池最小空闲连接
        max-idle: 5     # 连接池最大空闲连接
        max-active: 10  # 连接池最大连接数(使用负值表示没有限制)
        max-wait: -1    # 连接池最大阻塞等待时间(使用负值表示没有限制)

#===== Mybatis-plus 相关 =====
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  type-aliases-package: com.yc.core.*.entity
  configuration:
    map-underscore-to-camel-case: true  # \u9A7C\u5CF0
  global-config:
    banner: false #关闭MP 3.0 自带的banner
